name: jsonplaceholder
description: API Binding library for jsonplaceholder.
version: 1.0.0
homepage: https://github.com/glacion/jsonplaceholder-dart
author: Ahmetcan Guvendiren <ahmtcngvndrn@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  http: ^0.12.0
  meta: ^1.1.7
