name: jsonplaceholder
description: Package that provides API bindings for https://jsonplaceholder.typicode.com/
version: 1.1.1
homepage: https://github.com/glacion/jsonplaceholder-dart
author: Ahmetcan Guvendiren <ahmtcngvndrn@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  http: ^0.12.0
  meta: ^1.1.7
