name: jsonplaceholder
description: Package that provides API bindings for https://jsonplaceholder.typicode.com/
version: 2.0.0
homepage: https://github.com/glacion/jsonplaceholder-dart
author: Ahmetcan Guvendiren <ahmtcngvndrn@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  http: ^0.12.0
  meta: ^1.1.6
  built_value: ^6.5.0
  built_collection: ^4.2.2

dev_dependencies:
  build_runner: ^1.4.0
  built_value_generator: ^6.5.0
